version: '2.1'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: dockerfileweb
    working_dir: /var/www
    volumes_from:
    - app
    ports:
    - 8080:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=dynamicmenu"
    - "MYSQL_USER=root"
    - "MYSQL_PASSWORD="
    - "MYSQL_ROOT_PASSWORD="
    - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports:
    - "33061:3306"

volumes:
  dbdata:
